### ISSUE TITLE
How to build package locally?

### ISSUE THREAD

**Issue by shaunek-hero** [Client-Powered/qbo#10]
We found your package and we like it a lot and we wanted to use it and perhaps contribute back, but need a bit of help. We want to add some Purchase Order and Bill entity types, since our use case involves those.

I have the proper version of yarn installed and I have installed the dependencies and now I am just trying to do a compilation step and I am getting some type errors from tsc. 

If I run `tsc` it gives the following. Do you have any tips?

```
  src/lib/utils.ts:23:3 - error TS2322: Type 'Capitalize<Capitalize<T extends `${infer FirstPart}_${infer FirstLetter}${infer LastPart}` ? `${FirstPart}${Uppercase<FirstLetter>}${Capitalize<LastPart extends `${infer FirstPart}_${infer FirstLetter}${infer LastPart}` ? `${FirstPart}${Uppercase<FirstLetter>}${Capitalize<...>}` : LastPart>}` : T>>' is not assignable to type 'SnakeToCamelCase<T>'.
  Type 'Capitalize<string>' is not assignable to type 'SnakeToCamelCase<T>'.
    Type 'string' is not assignable to type 'SnakeToCamelCase<T>'.

 23   title(
      ~~~~~~
 24     str.replace(
    ~~~~~~~~~~~~~~~~
... 
 27     ) as SnakeToCamelCase<T>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 28   );
    ~~~

src/list.ts:31:10 - error TS2536: Type 'SnakeToCamelCase<T>' cannot be used to index type '{ [K in T as Capitalize<K extends `${infer FirstPart}_${infer FirstLetter}${infer LastPart}` ? `${FirstPart}${Uppercase<FirstLetter>}${Capitalize<LastPart extends `${infer FirstPart}_${infer FirstLetter}${infer LastPart}` ? `${FirstPart}${Uppercase<FirstLetter>}${Capitalize<...>}` : LastPart>}` : K> extends Capitali...'.

31       ...first.QueryResponse[Entity],
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/list.ts:32:10 - error TS2536: Type 'SnakeToCamelCase<T>' cannot be used to index type '{ [K in T as Capitalize<K extends `${infer FirstPart}_${infer FirstLetter}${infer LastPart}` ? `${FirstPart}${Uppercase<FirstLetter>}${Capitalize<LastPart extends `${infer FirstPart}_${infer FirstLetter}${infer LastPart}` ? `${FirstPart}${Uppercase<FirstLetter>}${Capitalize<...>}` : LastPart>}` : K> extends Capitali...'.

32       ...second.QueryResponse[Entity]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/list.ts:147:26 - error TS2536: Type 'Capitalize<T extends `${infer FirstPart}_${infer FirstLetter}${infer LastPart}` ? `${FirstPart}${Uppercase<FirstLetter>}${Capitalize<LastPart extends `${infer FirstPart}_${infer FirstLetter}${infer LastPart}` ? `${FirstPart}${Uppercase<FirstLetter>}${Capitalize<...>}` : LastPart>}` : T>' cannot be used to index type '{ [K in T as Capitalize<K extends `${infer FirstPart}_${infer FirstLetter}${infer LastPart}` ? `${FirstPart}${Uppercase<FirstLetter>}${Capitalize<LastPart extends `${infer FirstPart}_${infer FirstLetter}${infer LastPart}` ? `${FirstPart}${Uppercase<FirstLetter>}${Capitalize<...>}` : LastPart>}` : K> extends Capitali...'.

147   if (!opts.fetch_all || data.QueryResponse[Entity]?.length !== opts.limit) {
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~

src/list.ts:157:61 - error TS2339: Property 'length' does not exist on type 'NonNullable<({ [K in T as Capitalize<K extends `${infer FirstPart}_${infer FirstLetter}${infer LastPart}` ? `${FirstPart}${Uppercase<FirstLetter>}${Capitalize<LastPart extends `${infer FirstPart}_${infer FirstLetter}${infer LastPart}` ? `${FirstPart}${Uppercase<FirstLetter>}${Capitalize<...>}` : LastPart>}` : K> ext...'.

157           offset: opts.offset + data.QueryResponse[Entity]?.length
                                                                ~~~~~~

src/list.ts:224:15 - error TS2536: Type 'Capitalize<T extends `${infer FirstPart}_${infer FirstLetter}${infer LastPart}` ? `${FirstPart}${Uppercase<FirstLetter>}${Capitalize<LastPart extends `${infer FirstPart}_${infer FirstLetter}${infer LastPart}` ? `${FirstPart}${Uppercase<FirstLetter>}${Capitalize<...>}` : LastPart>}` : T>' cannot be used to index type '{ [K in T as Capitalize<K extends `${infer FirstPart}_${infer FirstLetter}${infer LastPart}` ? `${FirstPart}${Uppercase<FirstLetter>}${Capitalize<LastPart extends `${infer FirstPart}_${infer FirstLetter}${infer LastPart}` ? `${FirstPart}${Uppercase<FirstLetter>}${Capitalize<...>}` : LastPart>}` : K> extends Capitali...'.

224     entities: data?.QueryResponse[Entity] ?? [],
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/read.ts:83:13 - error TS2536: Type 'Capitalize<T extends `${infer FirstPart}_${infer FirstLetter}${infer LastPart}` ? `${FirstPart}${Uppercase<FirstLetter>}${Capitalize<LastPart extends `${infer FirstPart}_${infer FirstLetter}${infer LastPart}` ? `${FirstPart}${Uppercase<FirstLetter>}${Capitalize<...>}` : LastPart>}` : T>' cannot be used to index type 'QueryResponse<T>'.

83     entity: data[Entity],
               ~~~~~~~~~~~~

src/upsert.ts:82:13 - error TS2536: Type 'Capitalize<T extends `${infer FirstPart}_${infer FirstLetter}${infer LastPart}` ? `${FirstPart}${Uppercase<FirstLetter>}${Capitalize<LastPart extends `${infer FirstPart}_${infer FirstLetter}${infer LastPart}` ? `${FirstPart}${Uppercase<FirstLetter>}${Capitalize<...>}` : LastPart>}` : T>' cannot be used to index type 'QueryResponse<T>'.

82     entity: data[Entity],
               ~~~~~~~~~~~~


Found 8 errors in 4 files.

Errors  Files
     1  src/lib/utils.ts:23
     5  src/list.ts:31
     1  src/read.ts:83
     1  src/upsert.ts:82

```

**Comment by shaunek-hero** [comment]
@bigbizze Any chance you can help? I'm interested in possibly contributing back to this repo, but I'm a bit stuck right now.

**Comment by bigbizze** [comment]
> @bigbizze Any chance you can help? I'm interested in possibly contributing back to this repo, but I'm a bit stuck right now.

Yeah sure, let me get back to you later in the day tomorrow. I'm out of town on a vacation with the family right now.

**Comment by shaunek-hero** [comment]
@bigbizze Sorry to bug you about this, I know coming back from vacation can be a whirlwind, but if you have a moment I would really appreciate if you could give me a tip on this. We are interested in contributing back with a PR but our very near-term (urgent) need is to be able to build a package so we can iterate quickly with local development, and our next near-term need is to publish a version of your package to our private npm repo so we can go live with our changes very soon.

Our work will be focused on adding several entities including Purchase Order, Bill, and Item (with a focus on product items) and then after that we'll do some work with sales receipts as well.

So far I have run `yarn` to install the packages, and it would be great if you could give me the next steps. I normally would just run `tsc`/ to transpile to JS, and then use a variant of `npm publish`, but I'm stuck on the transpile step. So far I have tried running `npx tsc` and `./node_modules/typescript/bin/tsc`. This `tsc` binary is version 5.5.3.

**Comment by bigbizze** [comment]
> @bigbizze Sorry to bug you about this, I know coming back from vacation can be a whirlwind, but if you have a moment I would really appreciate if you could give me a tip on this. We are interested in contributing back with a PR but our very near-term (urgent) need is to be able to build a package so we can iterate quickly with local development, and our next near-term need is to publish a version of your package to our private npm repo so we can go live with our changes very soon.
> 
> Our work will be focused on adding several entities including Purchase Order, Bill, and Item (with a focus on product items) and then after that we'll do some work with sales receipts as well.
> 
> So far I have run `yarn` to install the packages, and it would be great if you could give me the next steps. I normally would just run `tsc`/ to transpile to JS, and then use a variant of `npm publish`, but I'm stuck on the transpile step. So far I have tried running `npx tsc` and `./node_modules/typescript/bin/tsc`. This `tsc` binary is version 5.5.3.

Hey, apologies for that, I'll get back to you tomorrow on this.

**Comment by bigbizze** [comment]
Hey @shaunek-hero, so as you can see here:
https://github.com/Client-Powered/qbo/blob/b0f3981a6727f3538c1253b2570658f752c1869f/package.json#L12

I just run `tsc` to transpile this usually.

I haven't got to my computer yet (still technically on vacation! we have a 3 month old son haha!), but I'm guessing the newer version of typescript you're using probably narrows the type further than was the case when I wrote this.

given that str.replace always returns a string, and that this function should work as intended (we do need some unit tests for this though at some point!), i think it should be safe to replace ` as SnakeToCamelCase<T>` here: https://github.com/Client-Powered/qbo/blob/b0f3981a6727f3538c1253b2570658f752c1869f/src/lib/utils.ts#L27

with ` as unknown as SnakeToCamelCase<T>` for the time being.

----

To address this properly:
1. We can use an earlier version of typescript to test the the case narrowing hypothesis
2. If 1 is true, we can figure out what about the type narrowing changes produced this issue, and whether there is a more idiomatic or elegant way to address the problem

That said, this *is* kind of a blackbox by virtue of the fact that typescript is fundamentally just a linter situation, regardless of the solution (unless I missed some significant changes in the last few versions haha). In other words, unit tests and casting as any or unknown is probably not the worst thing in the world here either.

----

I will stay on top of this more closely and get back to you more immediately going forward if you have any further issues. So please let me know if any further issues with this type pop-up after making this change, or if you have any other issues in general, and feel free to open a PR with those changes (and if you don't, I will get around to this relatively soon, but no promises here unfortunately as we have our hands full with the baby!). We would greatly appreciate it!

----

Edit: you might have to make similar changes in a few other places like here:

https://github.com/Client-Powered/qbo/blob/b0f3981a6727f3538c1253b2570658f752c1869f/src/lib/utils.ts#L80

**Comment by shaunek-hero** [comment]
@bigbizze Thanks a ton for your response, very helpful. I wish I could say I got it working but I didn't unfortunately :( I updated to typescript 5.2.2 and got the same errors as with version 5.5. 

I was able to sidestep the first compile error by moving the `as SnakeToCamelCase<T>` down one line, which was great, but I still couldn't get rid of the other TS errors in read.ts, list.ts, and upsert.ts. Those errors are all the same thing, and my Typescript skill appears to be insufficient to figure those ones out. I spent under 35 minutes looking at it so I can't say I did an exhaustive investigation, but I did confirm that my colleague is also running into the exact same TS errors. We are both on macos if that matters any.

I still would like to contribute back, but due to our really tight timeline I think what we need to do in the short term is use [patch-package](https://www.npmjs.com/package/patch-package) to patch your package to fit our needs. 

When you get back from your time off it would be really helpful if you could attempt to run `tsc` and see if you get the same errors we are getting after you clone it fresh from github, etc.

cc: @farjad6

**Comment by bigbizze** [comment]
@shaunek-hero ahh I'm sorry to hear that. We'll definitely figure this out when I'm back in the swing of things.

**Comment by shaunek-hero** [comment]
@bigbizze Sorry to bug you again, just checking in with you to see if you are back and in the swing of things. If not would you give me a heads up on your timeframe?

**Comment by bigbizze** [comment]
@shaunek-hero hey, no need to apologize. I should be fully back at this in two months or so (having an infant is a full-time job apparently 😅). were you running into further issues?

**Comment by shaunek-hero** [comment]
Okay thanks for the heads up. I have 5 kids myself, one still in diapers, and it does take a lot of work to get used to family life, good luck. 👍 

I don't have any "further issues," just the same issues from my original post 😄 Basically we can't get `tsc` to compile the Typescript into Javascript, and this is a blocker for us to be able to publish a fork or contribute back. Two of us have tried with multiple versions of Typescript. I did spend several hours trying to tweak some of the Typescript as you suggested, but I didn't get very far - it was like whack-a-mole, as I fix one issue it just raised more. And I wasn't ambitious enough to really do a big refactor. I'm skilled at Typescript but I'm not a giga chad. For the time being I have used `bun patch` to adjust the functionality that we need, but it isn't ideal.

I'm just confused how you could have compiled with tsc in the first place considering the code that is there - I've never had issues where, when using the same version of Typescript and the same tsconfig.json file two different computers had different results. If you have a few minutes sometime it would be really great if you could checkout the main branch and see if you are able to compile now as well.

**Comment by shaunek-hero** [comment]
Using patch files was not quite adequate so we figured out that we could just add maybe 5-7 `// @ts-ignore` comments to get around the compile issues. Now we have our changes published in a separate npm package. Maybe when you get back to work we can collaborate to merge some/all of our changes in to your package. Our fork is located here in case you want to check it out a bit https://github.com/herobullion/qbo.

**Comment by bigbizze** [comment]
working on this today. it seems like typescript has increased the strictness on type resolution since i wrote this

**Comment by bigbizze** [comment]
@shaunek-hero https://github.com/Client-Powered/qbo/pull/12/files should fix this

do you want to merge your branch into mine?

**Comment by shaunek-hero** [comment]
Okay thanks a lot, @bigbizze. We will pull in your fix into our branch. 🙏 

Regarding whether we merge our branch into yours, I think that is our end goal, however we made a couple changes that you may not want, I'm not so sure. I think next week I'll have time to merge that in and then maybe I'll do a PR and see if it makes sense to actually merge back into your repo.
